version: '3.0'

services:
    maddpg:
        image: aiminders/rl:latest
        container_name: maddpg
        command:
            make -f /root/maddpg/Makefile run
        volumes:
            - "..:/root/maddpg"
