name: CPU

on:
  push:
    branches: [ docker ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run build cpu
      run: |
        echo "build cpu"
        cd docker
        make cpu
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push aiminders/rl:latest
        docker logout
