name: Experiment

on:
    release:
        types:
            - created
    push:
        branches:
            - exp
            - lab
# 需要在windows设置:
#   https://github.com/microsoft/vscode-python/issues/2559
jobs:
    maddpg_exp:
        runs-on: lab
        timeout-minutes: 36000
        steps:
            - uses: actions/checkout@v2

            - name: MADDPG Experiment
              shell: cmd
              run: |
                whoami
                echo "run maddpg on lab"
                pip install -e . --user
                python -m maddpg.run --num_env 10  --env_batch_size 100 --num_agent 20
              env:
                  MADDPG_MINIO_SECRET: ${{ secrets.MADDPG_MINIO_SECRET }}
                  MADDPG_MINIO_KEY: ${{ secrets.MADDPG_MINIO_KEY }}
                  MADDPG_MINIO_HOST: ${{ secrets.MADDPG_MINIO_HOST }}
