name: lab

on:
    release:
        types:
            - created
    push:
        branches:
            - exp
            - lab
jobs:
    maddpg_exp:
        runs-on: lab
        timeout-minutes: 36000
        steps:
            - uses: actions/checkout@v2

            - name: MADDPG Experiment
              shell: powershell
              run: |
                docker-compose -f starter/docker_run.yml down
                docker system prune --force
                docker-compose -f starter/docker_run.yml up
