name: lab

on:
    release:
        types:
            - created
    push:
        branches:
            - exp
            - lab
# 需要在windows设置:
#   https://github.com/microsoft/vscode-python/issues/2559
jobs:
    maddpg_exp:
        runs-on: lab
        timeout-minutes: 36000
        steps:
            - uses: actions/checkout@v2

            - name: MADDPG Experiment
              shell: powershell
              run: |
                whoami
                echo "run maddpg on lab"
                docker system prune --force
                docker-compose -f starter/docker_run.yml up
